  ["SS-PoliceIL"] = { 
    _config = {vtype="car",blipid=357,blipcolor=77},

["SS-PoliceIL1"] = {"Police 1", 0, "<img class='CarImg' src='https://i.ibb.co/PsKvtdGd/1.png' width='100' height='50' >"},
["SS-PoliceIL2"] = {"Police 2", 0, "<img class='CarImg' src='https://i.ibb.co/SDdvwCv7/2.png' width='100' height='50' >"},
["SS-PoliceIL3"] = {"Police 3", 0, "<img class='CarImg' src='https://i.ibb.co/0ycbLgDD/3.png' width='100' height='50' >"},
["SS-PoliceIL4"] = {"Police 4", 0, "<img class='CarImg' src='https://i.ibb.co/1JwMsjDb/4.png' width='100' height='50' >"},
["SS-PoliceIL5"] = {"Police 5", 0, "<img class='CarImg' src='https://i.ibb.co/rKbsYRzx/5.png' width='100' height='50' >"},
["SS-PoliceIL6"] = {"Police 6", 0, "<img class='CarImg' src='https://i.ibb.co/V0Gf9bGn/6.png' width='100' height='50' >"},
["SS-PoliceIL7"] = {"Police 7", 0, "<img class='CarImg' src='https://i.ibb.co/fdvk8h2C/7.png' width='100' height='50' >"},
["SS-PoliceIL8"] = {"Police 8", 0, "<img class='CarImg' src='https://i.ibb.co/Z1bzfDSx/8.png' width='100' height='50' >"},
["SS-PoliceIL9"] = {"Police 9", 0, "<img class='CarImg' src='https://i.ibb.co/Wp6D5Wj7/9.png' width='100' height='50' >"},
["SS-PoliceIL10"] = {"Police 10", 0, "<img class='CarImg' src='https://i.ibb.co/FqjZYYGd/10.png' width='100' height='50' >"},
["SS-PoliceIL11"] = {"Police 11", 0, "<img class='CarImg' src='https://i.ibb.co/tTJ7km6g/11.png' width='100' height='50' >"},
["SS-PoliceIL12"] = {"Police 12", 0, "<img class='CarImg' src='https://i.ibb.co/NhKzXcB/12.png' width='100' height='50' >"},
["SS-PoliceIL13"] = {"Police 13", 0, "<img class='CarImg' src='https://i.ibb.co/0NMTZB3/13.png' width='100' height='50' >"},
["SS-PoliceIL14"] = {"Police 14", 0, "<img class='CarImg' src='https://i.ibb.co/FLj0zzCD/14.png' width='100' height='50' >"},
["SS-PoliceIL15"] = {"Police 15", 0, "<img class='CarImg' src='https://i.ibb.co/pjHRy4mR/15.png' width='100' height='50' >"},
},
